export const constants = {
  OK: "ok",
  ERROR: "error",
  NOT_FOUND: "not_found",
  ACCESS_DENIED: "access_denied",
  PERMISSION_DENIED: "permission_denied",
  REDIS_PREFIX:  "zochil_",
};

export const MONITORING_ROLES = {
  SHOP_VIEW: "shop_view",
  SHOP_MANAGE: "shop_manage",
  USER_VIEW: "user_view",
  USER_MANAGE: "user_manage",
  ORDER_VIEW: "order_view",
  ORDER_MANAGE: "order_manage",
  SETTLEMENT_VIEW: "settlement_view",
  SETTLEMENT_MANAGE: "settlement_manage",
  PRODUCT_VIEW: "product_view",
  PRODUCT_MANAGE: "product_manage",
  PRODUCT_CATEGORY_VIEW: "product_category_view",
  PRODUCT_CATEGORY_MANAGE: "product_category_manage",
  BROADCAST_VIEW: "broadcast_view",
  BROADCAST_MANAGE: "broadcast_manage",
  ISSUE_VIEW: "issue_view",
  ISSUE_MANAGE: "issue_manage",
  SELLER_VIEW: "seller_view",
  SELLER_MANAGE: "seller_manage",

  MARKETPLACE_SHOP_VIEW: "marketplace_shop_view",
  MARKETPLACE_SHOP_MANAGE: "marketplace_shop_manage",
  MARKETPLACE_POST_VIEW: "marketplace_post_view",
  MARKETPLACE_POST_MANAGE: "marketplace_post_manage",
  MARKETPLACE_PAGE_VIEW: "marketplace_page_view",
  MARKETPLACE_PAGE_MANAGE: "marketplace_page_manage",
  MARKETPLACE_BANNER_VIEW: "marketplace_banner_view",
  MARKETPLACE_BANNER_MANAGE: "marketplace_banner_manage",
  MARKETPLACE_PRODUCT_VIEW: "marketplace_product_view",
  MARKETPLACE_PRODUCT_MANAGE: "marketplace_product_manage",
  MARKETPLACE_CATEGORY_VIEW: "marketplace_category_view",
  MARKETPLACE_CATEGORY_MANAGE: "marketplace_category_manage",
  MARKETPLACE_SALE_CHANNEL_REQUEST_VIEW: "marketplace_sale_channel_request_view",
  MARKETPLACE_SALE_CHANNEL_REQUEST_MANAGE: "marketplace_sale_channel_request_manage"
}

export const RESERVED_UIDS = [
  'app',
  'api',
  'login',
  'zochil',
  'monitoring',
  'web',
  'dashboard',
  'admin',
  'secure',
  'booking',
  'hotel',
  'restaurant',
  'import',
  'unitel',
  'gmobile',
  'apu',
  'nomin',
  'mcs',
  'cocacola',
  'coca-cola',
  'tavanbogd',
  'tavan-bogd',
  'datacom',
  'arkhi',
  'orgil',
  'anungoo',
  'anun',
  'emart',
  'emartmall',
  'beer',
  'vodka',
  'wine',
  'fit',
  'fitness',
  'checkout',
  'account',
  'accounts',
  'sales',
  'promotion',
  'campaign',
];

export const SALE_CHANNELS = [
  "hipay",
  "supersale",
  "socialpay",
  "moodroom",
  "monpay",
  "darkhan",
  "erdenet",
  "lookbook",
  "lendmn",
  "khanbank",
  "redpoint",
  "pocket",
];

export default constants;
